### ISSUE TITLE
Add this to Omnipay driver list

### ISSUE THREAD

**Issue by znck** [razorpay/omnipay-razorpay#2]
http://omnipay.thephpleague.com/gateways/third-party/

**Comment by mayankamencherla** [comment]
@znck Were you able to manually test this by any chance?

**Comment by znck** [comment]
No! I didn't get time to test it. Would be needing it in near future.

**Comment by mayankamencherla** [comment]
@znck We do plan on adding it to the list, but could you please let us know once you test it? We will add it to the official list only once we are sure that it is error free and customers are able to use the module well.

**Comment by pradeep-sawant2501** [comment]
After integrating gateway and call purchase method I am getting redirect data are as follows but after getting below data not redirecting to https://checkout.razorpay.com/integration/shopify.

Redirect Data: Array
(
    [x_account_id] => rzp_test_aMmF72ZYyvCC8x
    [x_amount] => 101.00
    [x_currency] => INR
    [x_customer_email] => pradeep.callus7@gmail.com
    [x_customer_first_name] => Pradeep
    [x_customer_last_name] => Sawant
    [x_customer_billing_country] => IN
    [x_customer_billing_city] => Mumbai
    [x_customer_billing_address] => Ashokvan
    [x_customer_billing_state] => MH
    [x_customer_billing_zip] => 400066
    [x_customer_shipping_address1] => Ashokvan
    [x_customer_shipping_city] => Mumbai
    [x_customer_shipping_country] => IN
    [x_customer_shipping_first_name] => Pradeep
    [x_customer_shipping_last_name] => Sawant
    [x_customer_shipping_state] => MH
    [x_customer_shipping_zip] => 400066
    [x_description] => Test Pay
    [x_invoice] => #7639944951603981970
    [x_reference] => 7639944951603981970
    [x_shop_country] => IN
    [x_signature] => 47e91979e46191a433f76fd280a221577765c2c2108ef3df247b91fe57bc8e13
    [x_test] => 
    [x_url_callback] => https://example.com/call_razorpay
    [x_url_cancel] => https://example.com/call_razorpay
    [x_url_complete] => https://example.com/call_razorpay
)

Any help?

**Comment by vemulaharshith** [comment]
Did you got any resolution ? I am also getting the error( Invalid Order Details )please help me.
