### ISSUE TITLE
The requested package razorpay/omnipay-razorpay could not be found

### ISSUE THREAD

**Issue by re1nth** [razorpay/omnipay-razorpay#4]
Sir,
Adding the requirement "razorpay/omnipay-razorpay": "~2.0" in composer.json and running "**composer update**" didn't work for me. It says : 
Problem 1
    - The requested package razorpay/omnipay-razorpay could not be found in any version, there may be a typo in the package name.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by captn3m0** [comment]
The package isn't published yet. Please include it via a repository for now.
